# Generated by Django 3.0 on 2020-04-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200411_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='tutorial_detail',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
