# Generated by Django 3.0 on 2020-04-13 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200411_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='tutorial_detail',
        ),
        migrations.AddField(
            model_name='contributor',
            name='date1',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contributor',
            name='date10',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contributor',
            name='date2',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contributor',
            name='date3',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contributor',
            name='date4',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contributor',
            name='date5',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contributor',
            name='date6',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contributor',
            name='date7',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contributor',
            name='date8',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contributor',
            name='date9',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
